#!/bin/bash

###
#
# Execute the syndesis operator in isolation
#
# When developing the syndesis operator, the following scripts provide the build sequence:
#
# 1. syn-compile-op       -> Compile the operator to check for syntax errors
# 2. syn-install-op            -> Install the operator and upload it
# 3. syn-exec-op             -> Execute the operator to create a running syndesis
#
###

version=`oc version | grep -Eiv 'kubernetes|server' | grep -o '[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\?'`
echo "Using oc version $version"

if [[ "$version" = 4.* ]]; then
  DOMAIN="apps-crc.testing"
else
  DOMAIN="birds-of-prey.phantomjinx.org.uk"
fi

syndesis=$(cat << EOT
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
  name: "app"
spec:
  routeHostname: syndesis-syndesis.${DOMAIN}
  devSupport: true
EOT
)

echo "${syndesis}" | cat | oc create -f -
