#!/bin/bash

###
#
# Compile the syndesis operator locally using go
#
# NOTE. the GOPATH environment variable should be set if the operator project is
#             not installed under the default
#
# When developing the syndesis operator, the following scripts provide the build sequence:
#
# 1. syn-compile-op       -> Compile the operator to check for syntax errors
# 2. syn-build-op            -> Build the operator and upload the new image
# 3. syn-deploy-op         -> Deploy an instance of the operator
# 4. syn-exec-op             -> Execute the operator to create a running syndesis
#
###

if [ -z "$GOPATH" ]; then
  echo "To compile syndesis using go, the syndesis project should be located in the following location:"
  echo "\$GOPATH/src/github.com/src/syndesisio/syndesis"
  echo "The GOPATH env variable should be set according to conform to the location above"
  exit 1
fi

cd $GOPATH/src/github.com/syndesisio/syndesis/install/operator

source "$(pwd)/../../tools/bin/commands/util/common_funcs"
source "$(pwd)/../../tools/bin/commands/util/operator_funcs"
source "$(pwd)/../../tools/bin/commands/util/openshift_funcs"
source "./.lib.sh"

OPERATOR_BUILD_MODE="auto"
OPERATOR_IMAGE_NAME="docker.io/syndesis/syndesis-operator:latest"
SOURCE_GEN="on"

echo "OPERATOR_BUILD_MODE = $OPERATOR_BUILD_MODE"

build_operator $OPERATOR_BUILD_MODE "$SOURCE_GEN" \
  -ldflags "-X github.com/syndesisio/syndesis/install/operator/pkg.DefaultOperatorImage=$OPERATOR_IMAGE_NAME -X github.com/syndesisio/syndesis/install/operator/pkg.DefaultOperatorTag=$OPERATOR_IMAGE_TAG"
