#!/bin/bash

###
#
# Deploy an instance of the syndesis operator only
#
# When developing the syndesis operator, the following scripts provide the build sequence:
#
# 1. syn-compile-op       -> Compile the operator to check for syntax errors
# 2. syn-build-op            -> Build the operator and upload the new image
# 3. syn-deploy-op         -> Deploy an instance of the operator
# 4. syn-exec-op             -> Execute the operator to create a running syndesis
#
###

SYNDESIS="$HOME/programming/java/syndesis"

oc create -f $SYNDESIS/install/operator/deploy/syndesis-operator.yml
