#!/bin/bash

###
#
# Compile the syndesis operator locally using go
#
# NOTE. the GOPATH environment variable should be set if the operator project is
#             not installed under the default
#
# When developing the syndesis operator, the following scripts provide the build sequence:
#
# 1. syn-compile-op       -> Compile the operator to check for syntax errors
# 2. syn-install-op           -> Install the operator and upload it
# 3. syn-exec-op             -> Execute the operator to create a running syndesis
#
###

while getopts s option
do
  case "${option}"
  in
    s) SRCGENSKIP=1;;
  esac
done

if [ -z "$GOPATH" ]; then
  echo "To compile syndesis using go, the syndesis project should be located in the following location:"
  echo "\$GOPATH/src/github.com/src/syndesisio/syndesis"
  echo "The GOPATH env variable should be set according to conform to the location above"
  exit 1
fi

cd $GOPATH/src/github.com/syndesisio/syndesis/install/operator

operators=$(find $GOPATH -name syndesis-operator)
for op in ${operators}
do
  rm -rf ${op}
done

source "$(pwd)/../../tools/bin/commands/util/common_funcs"
source "$(pwd)/../../tools/bin/commands/util/operator_funcs"
source "$(pwd)/../../tools/bin/commands/util/openshift_funcs"
source "./.lib.sh"

OPERATOR_IMAGE_NAME="$(readopt --image-name         docker.io/syndesis/syndesis-operator)"
OPERATOR_IMAGE_TAG="$(readopt  --image-tag          latest)"
S2I_STREAM_NAME="$(readopt     --s2i-stream-name    syndesis-operator)"
OPERATOR_BUILD_MODE="$(readopt --operator-build     auto)"
IMAGE_BUILD_MODE="$(readopt    --image-build        auto)"
SOURCE_GEN="$(readopt          --source-gen         on)"
GO_BUILD_OPTIONS="$(readopt    --go-options         '')"
GO_PROXY_URL="$(readopt        --go-proxy           https://proxy.golang.org)"

if [ "$SRCGENSKIP" == "1" ]; then
  SOURCE_GEN="off"
fi

echo "OPERATOR_BUILD_MODE = $OPERATOR_BUILD_MODE"

branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch == *1.9* ]]; then
  echo "Neutralising GO_PROXY_URL"
  build_operator $OPERATOR_BUILD_MODE "$SOURCE_GEN" \
    -ldflags "-X github.com/syndesisio/syndesis/install/operator/pkg.DefaultOperatorImage=${OPERATOR_IMAGE_NAME} -X github.com/syndesisio/syndesis/install/operator/pkg.DefaultOperatorTag=${OPERATOR_IMAGE_TAG}" ${GO_BUILD_OPTIONS}
else
  build_operator $OPERATOR_BUILD_MODE "$SOURCE_GEN" "$GO_PROXY_URL" \
    -ldflags "-X github.com/syndesisio/syndesis/install/operator/pkg.DefaultOperatorImage=${OPERATOR_IMAGE_NAME} -X github.com/syndesisio/syndesis/install/operator/pkg.DefaultOperatorTag=${OPERATOR_IMAGE_TAG}" ${GO_BUILD_OPTIONS}
fi
