#!/bin/bash

###
#
# Remove & recreate the syndesis project
# Requires oc-recreate-project script
#
###

oc-login-admin
oc delete crd/jaegers.jaegertracing.io crd/syndesises.syndesis.io crd/camel-k:edit

crbs=$(oc get clusterrolebindings | grep 'syndesis\|camel\|jaeger' | awk '{print $1}')
for crb in $crbs
do
  oc delete clusterrolebinding $crb
done

oc-login
oc-recreate-project syndesis
