#!/bin/bash

###
#
# Delete those pods that conform to the given pattern
#
###

TYPE="$1"
if [ -z "$TYPE" ]; then
  echo "$0 <pattern-of-builds-to-find>"
  exit 1
fi

PODS=$(oc get pods | grep "${TYPE}" | awk {'print "po/"$1'})
echo -e "Pods to be deleted:\n${PODS}"
if [ -z "$PODS" ]; then
  echo "No pods found"
  exit 1
fi

echo "Deleting pods ..."
for POD in ${PODS}
do
  oc delete "${POD}"
done
