#!/bin/bash

for i in $(seq -f "%04g" 1 100)
do
  pv="pv$i"

  oc get pv/$pv | grep Failure
  if [ "$?" == "1" ]; then
    echo "$pv has not failed ... skipping"
    continue # pv is fine
  fi

  echo "Patching $pv to remove claim reference"
  oc patch pv/$pv --type json -p '[{ "op": "remove", "path": "/spec/claimRef" }]'
done
