#!/bin/bash

###
#
# Create the named project, first deleting it if
# it already exists.
#
###

if [ -z "$1" ]; then
  echo "$0 <project-name>"
  exit 1
fi

if oc get project | grep "$1"; then
  oc delete project "$1"

  while oc get project | grep "$1"
  do
    sleep 3
  done

  sleep 5
fi

sleep 5

PROJECT=0
while [ $PROJECT == 0 ];
do
  oc new-project "$1"
  if [ $? -eq 0 ]; then
    PROJECT=1
  fi

  sleep 3
done
